// eslint-disable-next-line @typescript-eslint/no-unused-vars
export enum Role {
  USER = 'USER',
  ADMIN = 'ADMIN',
  MERCHANT = 'MERCHANT',
  MARKETER = 'MARKETER',
  LEVEL1 = 'LEVEL1',
  LEVEL2 = 'LEVEL2',
  LEVEL3 = 'LEVEL3',
  LEVEL4 = 'LEVEL4',
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export enum OtpType {
  Login = 'Login',
  RessetPass = 'RessetPass',
}

export enum OrderType {
  billByCredit = 'billByCredit',
  billByWallet = 'billByWallet',
  internetByWallet = 'internetByWallet',
  internetByCredit = 'internetByCredit',
  chargeByWallet = 'chargeByWallet',
  chargeByCredit = 'chargeByCredit',
  walletToWallet = 'walletToWallet', //done
  increaseWallet = 'increaseWallet', // done
  creditToOtherWallet = 'creditToOtherWallet',
  DRIVING_LICENSE_BY_WALLET = 'DRIVING_LICENSE_BY_WALLET',
  DRIVING_LICENSE_BY_CREDIT = 'DRIVING_LICENSE_BY_CREDIT',
  NEGETIVE_POINT_BY_WALLET = 'NEGETIVE_POINT_BY_WALLET',
  NEGETIVE_POINT_BY_CREDIT = 'NEGETIVE_POINT_BY_CREDIT',
  ACTIVE_PLATES_BY_WALLET = 'ACTIVE_PLATES_BY_WALLET',
  ACTIVE_PLATES_BY_CREDIT= 'ACTIVE_PLATES_BY_CREDIT',
  PASSPORT_STATUS_BY_WALLET = 'PASSPORT_STATUS_BY_WALLET',
  PASSPORT_STATUS_BY_CREDIT = 'PASSPORT_STATUS_BY_CREDIT',
  COUNTRY_LEAVING_BY_WALLET = 'COUNTRY_LEAVING_BY_WALLET',
  COUNTRY_LEAVING_BY_CREDIT = 'COUNTRY_LEAVING_BY_CREDIT',
  VIOLATION_REPORT_BY_WALLET = 'VIOLATION_REPORT_BY_WALLET',
  VIOLATION_REPORT_BY_CREDIT = 'VIOLATION_REPORT_BY_CREDIT',
  VIOLATION_IMAGE_BY_WALLET = 'VIOLATION_IMAGE_BY_WALLET',
  VIOLATION_IMAGE_BY_CREDIT = 'VIOLATION_IMAGE_BY_CREDIT',
  VIOLATION_AGGREGATE_BY_WALLET = 'VIOLATION_AGGREGATE_BY_WALLET',
  VIOLATION_AGGREGATE_BY_CREDIT = 'VIOLATION_AGGREGATE_BY_CREDIT',
  VIOLATION_AGGREGATE_NO_AUTH_BY_CREDIT = 'VIOLATION_AGGREGATE_NO_AUTH_BY_CREDIT',
  DOCUMENT_STATUS_BY_WALLET = 'DOCUMENT_STATUS_BY_WALLET',
  DOCUMENT_STATUS_BY_CREDIT = 'DOCUMENT_STATUS_BY_CREDIT',
}
export enum CashbackState {
  PENDING = 'PENDING', // is pernding to cash back
  DONE = 'DONE', // cash back is done
  REJECTED = 'REJECTED', // cash back is not done
}

export enum NajiType {
  DRIVING_LICENSE = 'DRIVING_LICENSE',
  NEGETIVE_POINT = 'NEGETIVE_POINT',
  ACTIVE_PLATES = 'ACTIVE_PLATES',
  PASSPORT_STATUS = 'PASSPORT_STATUS',
  COUNTRY_LEAVING = 'COUNTRY_LEAVING',
  VIOLATION_REPORT = 'VIOLATION_REPORT',
  VIOLATION_IMAGE = 'VIOLATION_IMAGE',
  VIOLATION_AGGREGATE = 'VIOLATION_AGGREGATE',
  VIOLATION_AGGREGATE_NO_AUTH = 'VIOLATION_AGGREGATE_NO_AUTH',
  DOCUMENT_STATUS = 'DOCUMENT_STATUS',
}

export enum PlateType {
  MOTOR = 'MOTOR',
  CAR = 'CAR',
}
